// Route constants

export const ADMIN_ROUTES = {
  DASHBOARD: '/admin/dashboard',
  CATEGORIES: '/admin/categories',
  CATEGORIES_CREATE: '/admin/categories/create',
  CATEGORIES_EDIT: (id: string) => `/admin/categories/${id}/edit`,
  BUSINESSES: '/admin/businesses',
  BUSINESSES_PENDING: '/admin/businesses/pending',
  BUSINESSES_DETAIL: (id: string) => `/admin/businesses/${id}`,
  USERS: '/admin/users',
  USERS_DETAIL: (id: string) => `/admin/users/${id}`,
  PAYMENTS: '/admin/payments',
  PAYMENTS_REFUNDS: '/admin/payments/refunds',
  PAYMENTS_SETTLEMENTS: '/admin/payments/settlements',
  WALLETS_MERCHANTS: '/admin/wallets/merchants',
  WALLETS_USERS: '/admin/wallets/users',
  REPORTS_TRANSACTIONS: '/admin/reports/transactions',
  REPORTS_BUSINESSES: '/admin/reports/businesses',
  REPORTS_FINANCIAL: '/admin/reports/financial',
  SUPPORT_TICKETS: '/admin/support/tickets',
  SUPPORT_DISPUTES: '/admin/support/disputes',
  SETTINGS_PAYMENT: '/admin/settings/payment',
  SETTINGS_PLATFORM: '/admin/settings/platform',
  SETTINGS_SECURITY: '/admin/settings/security',
  NOTIFICATIONS_SEND: '/admin/notifications/send',
  NOTIFICATIONS_HISTORY: '/admin/notifications/history',
  LOGIN: '/auth/admin/login',
} as const;

export const SUPER_ADMIN_ROUTES = {
  DASHBOARD: '/super-admin/dashboard',
  ADMINS: '/super-admin/admins',
  ADMINS_CREATE: '/super-admin/admins/create',
  ADMINS_EDIT: (id: string) => `/super-admin/admins/${id}/edit`,
  ROLES: '/super-admin/roles',
  ROLES_CREATE: '/super-admin/roles/create',
  ROLES_EDIT: (id: string) => `/super-admin/roles/${id}/edit`,
  ACTIVITY_LOGS: '/super-admin/activity-logs',
  SYSTEM_SETTINGS: '/super-admin/system/settings',
  SYSTEM_HEALTH: '/super-admin/system/health',
  LOGIN: '/auth/super-admin/login',
} as const;

export const PUBLIC_ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  FEATURES: '/features',
  PRICING: '/pricing',
  CONTACT: '/contact',
  STORES: '/stores',
  STORE_DETAIL: (id: string) => `/stores/${id}`,
} as const;

export const USER_ROUTES = {
  HOME: '/',
  CATEGORIES: '/categories',
  CATEGORY_DETAIL: (slug: string) => `/categories/${slug}`,
  SEARCH: '/search',
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  DELIVERY_SLOTS: '/checkout/delivery-slots',
  SIGNUP: '/auth/signup',
  LOGIN: '/auth/login',
  PROFILE: '/account',
  PROFILE_ADDRESSES: '/account/addresses',
  PROFILE_PAYMENT_METHODS: '/account/payment-methods',
  PROFILE_PREFERENCES: '/account/preferences',
  ORDERS: '/orders',
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ORDER_TRACKING: (id: string) => `/orders/${id}/track`,
  SUBSCRIPTIONS: '/subscriptions',
  SUBSCRIPTION_DETAIL: (id: string) => `/subscriptions/${id}`,
  PAYMENT: '/payment',
  WALLET: '/wallet',
  OFFERS: '/offers',
  NUTRITION_FILTER: '/nutrition-filter',
  REVIEWS: '/reviews',
  WISHLIST: '/wishlist',
  VENDOR_DETAIL: (id: string) => `/vendors/${id}`,
  STORE_LOCATOR: '/store-locator',
  SUPPORT: '/support',
  REFUND: '/refund',
  REFUND_DETAIL: (id: string) => `/refund/${id}`,
  CHECKOUT_CONFIRMATION: '/checkout/confirmation',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  DELIVERY_POLICY: '/delivery-policy',
  REFUND_POLICY: '/refund-policy',
  ONBOARDING: '/onboarding',
  REFERRAL: '/referral',
  NOTIFICATIONS: '/notifications',
} as const;

